import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Essential Cotton Tee',
    description: 'A premium heavy-weight cotton tee with a relaxed fit.',
    price: 45,
    category: 'Apparel',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    reviews: 124,
    stock: 50,
  },
  {
    id: '2',
    name: 'Minimalist Leather Tote',
    description: 'Handcrafted Italian leather tote for daily essentials.',
    price: 180,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1544816153-16ad4614455a?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    reviews: 86,
    stock: 15,
  },
  {
    id: '3',
    name: 'Performance Tech Shorts',
    description: 'Water-resistant, stretch fabric for maximum mobility.',
    price: 65,
    category: 'Activewear',
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    reviews: 210,
    stock: 30,
  },
  {
    id: '4',
    name: 'Signature Wool Sweater',
    description: 'Ethically sourced merino wool with a timeless knit pattern.',
    price: 120,
    category: 'Apparel',
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    reviews: 45,
    stock: 20,
  },
  {
    id: '5',
    name: 'Ceramic Pour-Over Set',
    description: 'Hand-glazed ceramic dripper and carafe for the perfect brew.',
    price: 85,
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1544350223-99ff9c42744e?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    reviews: 67,
    stock: 12,
  },
  {
    id: '6',
    name: 'Canvas Weekender Bag',
    description: 'Durable waxed canvas with leather accents for short trips.',
    price: 145,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    reviews: 93,
    stock: 8,
  },
];
